import { z } from 'zod';

/**
 * JSON contract for POST /telemetry.
 *
 * The Raspberry Pi (Process B) batches readings from its SQLite outbox and
 * posts them here. Each individual reading carries its own `reading_id` for
 * idempotency, so a repeated delivery (after a network blip or outbox redrive)
 * never produces duplicate rows.
 *
 * Keep this schema in lockstep with the Pi-side serializer. When fields change,
 * bump the contract in docs/telemetry-contract.md too so Chris/Emmanuel notice.
 */

const UUID = z.string().uuid();

const ISO_TIMESTAMP = z.string().datetime({ offset: true }).describe('ISO 8601 timestamp with timezone, e.g. 2026-04-21T08:30:00Z');

/**
 * Pi-level health metrics. Optional because:
 *  - Sending them on every batch would be wasteful (they change slowly)
 *  - Early Pi firmware may not wire them up yet
 *
 * These are merged into `shelves.metadata` by the handler (not persisted per-reading),
 * so omitting them simply leaves the previously-reported values in place.
 */
const MetadataSchema = z
	.object({
		battery: z.number().min(0).max(100).optional().describe('Battery percentage 0-100'),
		rssi: z.number().int().min(-120).max(0).optional().describe('WiFi signal strength in dBm; typical range -90 (weak) to -30 (strong)'),
	})
	.strict();

/**
 * One weight sample from one scale. `scale_index` is the Pi-side hardware ID
 * (0-based) for the weighing station; the backend resolves it to a
 * `shelf_items.id` via (shelf_id, scale_index) on insert.
 *
 * `est_grams` is the Pi's cleaned output after Process A's averaging and
 * calibration; the backend does NOT re-filter it, only computes state from it.
 */
const ReadingSchema = z
	.object({
		reading_id: UUID.describe('UUIDv4 generated by Process B when queuing the reading; the dedup key'),
		scale_index: z.number().int().nonnegative(),
		est_grams: z.number().finite().nonnegative(),
	})
	.strict();

const MAX_BATCH_SIZE = 100;

export const TelemetryPayloadSchema = z
	.object({
		shelf_id: UUID,
		sampled_at: ISO_TIMESTAMP,
		metadata: MetadataSchema.optional(),
		readings: z.array(ReadingSchema).min(1).max(MAX_BATCH_SIZE),
	})
	.strict();

export type TelemetryPayload = z.infer<typeof TelemetryPayloadSchema>;
export type TelemetryReading = z.infer<typeof ReadingSchema>;
export type TelemetryMetadata = z.infer<typeof MetadataSchema>;

export const TELEMETRY_LIMITS = {
	MAX_BATCH_SIZE,
	/** Readings more than this far in the future are rejected as clock-skew bugs. */
	MAX_FUTURE_SKEW_MS: 60 * 60 * 1000,
	/** Readings older than this are accepted but logged — they're almost certainly an outbox drain. */
	STALE_WARN_MS: 30 * 24 * 60 * 60 * 1000,
} as const;
